In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine , text
import psycopg2

##### creating connection to postrgesql

In [3]:
# fromat : postgresql://username:password@host:5432/database

engine =create_engine('postgresql://postgres:8765@localhost:5432/data_mastery_db')

##### testing connection

In [11]:
with engine.connect() as conn: result = conn.execute(text('SELECT 1'))
print("conencted to Postgres")

conencted to Postgres

##### laoding csv tempoarary

In [23]:
raw_df = pd.read_csv('../01_retail_pipeline/data/online_retail_II.csv')

print(f'shape: {raw_df.shape}')
print(f'columns {raw_df.columns.to_list}')
print(f'\n {raw_df.head()}')

shape: (1067371, 8)
columns <bound method IndexOpsMixin.tolist of Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')>

   Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1  489434    79323P                   PINK CHERRY LIGHTS        12
2  489434    79323W                  WHITE CHERRY LIGHTS        12
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

           InvoiceDate  Price  Customer ID         Country
0  2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1  2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2  2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3  2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4  2009-12-01 07:45:00   1.25      13085.0  United Kingdom

##### Exploring before pushing to db

In [19]:
print(raw_df.dtypes)
print(f'\n Null : {raw_df.isnull().sum()}')

Invoice            str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
dtype: object

 Null : Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

##### pushing to postgres

In [ ]:
# this creates a table 'retail_transactions' in db

raw_df.to_sql('retail_transactions', engine, if_exists = 'replace', index = False)

371

In [37]:
count = pd.read_sql('select count(*) as total from retail_transactions', engine)
print(f'rows: {count['total'][0]}')

rows: 1067371

In [27]:
del raw_df

##### queries

In [29]:
df_sample = pd.read_sql('select * from retail_transactions limit 5', engine)
df_sample

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [33]:
# how amny unique customers

pd.read_sql('select count(distinct "Customer ID") as unique_customers from retail_transactions', engine)

   unique_customers
0              5942

In [34]:
# Top 10 countries by transaction count
pd.read_sql('''
    SELECT "Country", COUNT(*) as order_count 
    FROM retail_transactions 
    GROUP BY "Country" 
    ORDER BY order_count DESC 
    LIMIT 10
''', engine)

          Country  order_count
0  United Kingdom       981330
1            EIRE        17866
2         Germany        17624
3          France        14330
4     Netherlands         5140
5           Spain         3811
6     Switzerland         3189
7         Belgium         3123
8        Portugal         2620
9       Australia         1913

##### now pull data from dataset from Pandas

In [35]:
df = pd.read_sql('select * from retail_transactions', engine)

print(f"Shape: {df.shape}")
print(f"\nNull counts:\n{df.isnull().sum()}")
print(f"\nDtypes:\n{df.dtypes}")

Shape: (1067371, 8)

Null counts:
Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

Dtypes:
Invoice            str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
dtype: object

##### Find cancelled orders they have starting with C in invoice No.

In [43]:
cancelled = df[df['Invoice'].str.startswith('C' , na = False)]

print(f'total rows: {len(df)}')
print(f'cancelled: {len(cancelled)}')
print(f"Percentage: {len(cancelled)/len(df)*100:.1f}%")
print(f"\nSample cancelled rows:")
cancelled.head()

total rows: 1067371
cancelled: 19494
Percentage: 1.8%

Sample cancelled rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [45]:
df_clean = df[~df['Invoice'].str.startswith('C' , na = False).copy()]

print(f'brfor: {len(df)} , after: {len(df_clean)}')
print(f"Removed: {len(df) - len(df_clean)}")

brfor: 1067371 , after: 1047877
Removed: 19494

##### Now even afetr removing cancellation there can be bad quantities like 0 or -ve values that arent real trasactions

In [60]:
bad_qty = df_clean[df_clean['Quantity'] <= 0]
print(f'total bad quantities: {len(bad_qty)}')

# bad prices

bad_prices = df_clean[df_clean['Price'] <= 0]
print(f'bad prices: {len(bad_prices)}')

total bad quantities: 0
bad prices: 0

In [55]:
# sampling them 

if len(bad_qty) > 0:
    print(f"\nSample bad quantities:")
    print(bad_qty.head())
    
if len(bad_prices) > 0:
    print(f"\nSample bad prices:")
    print(bad_prices.head())

Sample bad quantities:
    Invoice StockCode   Description  Quantity          InvoiceDate  Price  \
263  489464     21733  85123a mixed       -96  2009-12-01 10:52:00    0.0
283  489463     71477         short      -240  2009-12-01 10:52:00    0.0
284  489467    85123A   21733 mixed      -192  2009-12-01 10:53:00    0.0
470  489521     21646           NaN       -50  2009-12-01 11:44:00    0.0
718  490384     84721           NaN       -42  2009-12-05 14:00:00    0.0

     Customer ID         Country
263          NaN  United Kingdom
283          NaN  United Kingdom
284          NaN  United Kingdom
470          NaN  United Kingdom
718          NaN  United Kingdom

Sample bad prices:
    Invoice StockCode   Description  Quantity          InvoiceDate  Price  \
263  489464     21733  85123a mixed       -96  2009-12-01 10:52:00    0.0
283  489463     71477         short      -240  2009-12-01 10:52:00    0.0
284  489467    85123A   21733 mixed      -192  2009-12-01 10:53:00    0.0
470  489521     21646           NaN       -50  2009-12-01 11:44:00    0.0
718  490384     84721           NaN       -42  2009-12-05 14:00:00    0.0

     Customer ID         Country
263          NaN  United Kingdom
283          NaN  United Kingdom
284          NaN  United Kingdom
470          NaN  United Kingdom
718          NaN  United Kingdom

In [59]:
# Remove rows where Quantity <= 0 OR Price <= 0
df_clean = df_clean[(df_clean['Quantity'] > 0) & (df_clean['Price'] > 0)].copy()
print(f"After removing bad qty/price: {len(df_clean)}")

After removing bad qty/price: 1041670

##### nulls

In [61]:
df_clean.isnull().sum()

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    236121
Country             0
dtype: int64

In [62]:
# Version 1: Full data (for product/revenue analysis)
df_all = df_clean.copy()

# Version 2: Customer data only (for customer behavior analysis)
df_customers = df_clean.dropna(subset=['Customer ID']).copy()

print(f"Full data:     {len(df_all)} rows")
print(f"Customer data: {len(df_customers)} rows")
print(f"Dropped:       {len(df_all) - len(df_customers)} ({(len(df_all) - len(df_customers))/len(df_all)*100:.1f}%)")

Full data:     1041670 rows
Customer data: 805549 rows
Dropped:       236121 (22.7%)

##### duplicates

In [63]:
dupes = df_customers.duplicated().sum()
print(f'Duplicated rows: {dupes}  ({dupes/len(df_customers)*100:.1f}%)')

df_customers = df_customers.drop_duplicates().copy()
print(f"After dedup: {len(df_customers)}")

Duplicated rows: 26124  (3.2%)
After dedup: 779425

In [64]:
df_customers['InvoiceDate'] = pd.to_datetime(df_customers['InvoiceDate'])
print(df_customers['InvoiceDate'].dtype)

print(f"\nDate range: {df_customers['InvoiceDate'].min()} to {df_customers['InvoiceDate'].max()}")

datetime64[us]

Date range: 2009-12-01 07:45:00 to 2011-12-09 12:50:00

In [65]:
# total price cal.

df_customers['TotalPrice'] = df_customers['Quantity'] * df_customers['Price']
df_customers.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,39.6
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom,59.5
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,30.6
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom,45.0

In [66]:
# Cleaning summary
print("CLEANING PIPELINE SUMMARY")
print(f"Raw data:              1,067,371 rows")
print(f"After cancel removal:  1,047,877 rows  (-19,494)")
print(f"After bad qty/price:   1,041,670 rows  (-6,207)")
print(f"After null customers:    805,549 rows  (-236,121)")
print(f"After dedup:             779,425 rows  (-26,124)")
print(f"\nTotal removed: {1067371 - 779425} rows ({(1067371 - 779425)/1067371*100:.1f}%)")
print(f"Columns: {list(df_customers.columns)}")
print(f"Date range: {df_customers['InvoiceDate'].min()} to {df_customers['InvoiceDate'].max()}")
print(f"Null check:\n{df_customers.isnull().sum()}")

CLEANING PIPELINE SUMMARY
Raw data:              1,067,371 rows
After cancel removal:  1,047,877 rows  (-19,494)
After bad qty/price:   1,041,670 rows  (-6,207)
After null customers:    805,549 rows  (-236,121)
After dedup:             779,425 rows  (-26,124)

Total removed: 287946 rows (27.0%)
Columns: ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country', 'TotalPrice']
Date range: 2009-12-01 07:45:00 to 2011-12-09 12:50:00
Null check:
Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
TotalPrice     0
dtype: int64

##### save new data back to db

In [67]:
df_customers.to_sql('retail_clean' , engine , if_exists='replace' , index=False)
print(f"Saved {len(df_customers)} rows to 'retail_clean' table")

Saved 779425 rows to 'retail_clean' table